name: Build Electron App

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Build and release electron app
    runs-on: windows-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Cleanup Artifacts
        run: |
          npx rimraf "dist/electron/!(*.exe)" "dist/electron/(*-unpacked)"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: windows-latest
          path: dist/electron

      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "dist/electron/**"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
